octopus:
  environments:
    - development
    - production
  replicated: true
  fully_replicated: true
  development:
    slave1:
      adapter: mysql2
      host: localhost
      database: mint2
      username: root
  production:
    slave1:
      adapter: mysql2
      host: localhost
      database: mint2
      username: root