octopus:
  environments:
    - development
    - production
  replicated: true
  fully_replicated: true
  development:
    slave1:
      adapter: mysql2
      host: localhost
      database: mint2
      username: root
    slave2:
      adapter: mysql2
      host: localhost
      database: mint
      username: root
  production:
    slave1:
      adapter: mysql2
      host: mint-multiple-latlongindexing.cz2moefkl3s1.us-west-2.rds.amazonaws.com
      database: rails_app
      username: root
      password: password
    slave2:
      adapter: mysql2
      database: rails_app