octopus:
  environments:
    - development
    - production
  replicated: true
  fully_replicated: true
  development:
    slave2:
      adapter: mysql2
      host: localhost
      database: mint
      username: root
    slave1:
      adapter: mysql2
      host: localhost
      database: mint2
      username: root
  production:
    slave1:
      adapter: mysql2
      host: mint-rdsonly-m3medium.cz2moefkl3s1.us-west-2.rds.amazonaws.com
      database: rails_app
      username: root
      password: password
    slave2:
      adapter: mysql2
      database: rails_app
    slave3:
      adapter: mysql2
      host: mint-base-multi.cz2moefkl3s1.us-west-2.rds.amazonaws.com
      database: rails_app
      username: root
      password: password
    slave4:
      adapter: mysql2
      host: mint-shard3-bada.cz2moefkl3s1.us-west-2.rds.amazonaws.com
      database: rails_app
      username: root
      password: password